Add basic coverage to RailsStats::CodeStatistics#to_s
bleonard/rails_stats pull request #10
Opened 2020-10-07 03:48 UTC by etagwerker

Hey @bleonard, 

This PR adds minitest to the project and it adds a simple scenario for `RailsStats::CodeStatistics#to_s`

I added a Rails 6.0 application in test/dummy to make it easier to test `rails_stats`. I didn't want to add a lot of tests before getting your feedback. Do you think this is a step in the right direction? 

Please let me know. 

Thanks!

2020-10-07 22:51 UTC, bleonard commented
That's certainly a bunch of files, but guess they are all in the test directory.
Feel free to give it a shot if you want. I didn't even know people were using this project :-)

2020-10-09 18:35 UTC, etagwerker commented
@bleonard Cool, thanks! Do you think this is ready to be merged? I just solved the conflict. 😄

2020-10-09 18:36 UTC, etagwerker commented
@bleonard One more thing, could you enable Travis CI for this project? Or do you prefer checks with GitHub Actions?

2020-10-14 20:08 UTC, arielj requested changes
It would be nice to have a section in the README explaining how to run the tests of the gem.

2020-10-14 20:08 UTC, arielj commented on Rakefile
> -require "rails_stats"
Removing this lines makes the rake command unable to find the `stats` task.

2020-10-14 20:08 UTC, arielj commented on test/test_helper.rb
> +require "rails_stats/all"
Just nit picking here, but it's warning about a missing trailing new line

2020-10-15 03:00 UTC, etagwerker commented
@arielj Thanks for review this PR! Just addressed your comments 👍

2020-10-15 14:29 UTC, arielj approved these changes
Looks good!

2020-10-15 15:12 UTC, merged